### ISSUE TITLE
HW 3 COMPLETE

### ISSUE THREAD

**Issue by HannahCBrunelle** [HannahCBrunelle/Brunelle_SpatialEcology#5]

**Comment by fitzLab-AL** [comment]
Hi @HannahCBrunelle - Please see my comments on your script and the solution. Your code produced way too few sampling points and should have looked similar to Figure 1 in the assignment. There were also several questions that were not answered correctly.

If you have any questions or would like to go over the assignment together, please let me know.

GRADE: 6/10
